DROP DATABASE IF EXISTS session02;
CREATE DATABASE session02;
USE session02;

/*
Phân tích:
- Email có thể bị trùng hoặc trống
- Tuổi có thể âm hoặc bằng 0

CREATE TABLE CUSTOMERS (
		CustomerID INT PRIMARY KEY,
        FullName VARCHAR(100),
		Email VARCHAR(100),
        Age INT
);
*/

CREATE TABLE CUSTOMERS (
		CustomerID INT PRIMARY KEY,
        FullName VARCHAR(100),
		Email VARCHAR(100),
        Age INT
);

ALTER TABLE CUSTOMERS DROP COLUMN Email;
ALTER TABLE CUSTOMERS DROP COLUMN FullName;
ALTER TABLE CUSTOMERS DROP COLUMN Age;

ALTER TABLE CUSTOMERS 
ADD COLUMN FullName VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS 
ADD COLUMN Email VARCHAR(100) NOT NULL UNIQUE;

ALTER TABLE CUSTOMERS 
ADD COLUMN Age INT CHECK (Age > 0 AND Age <= 100);